# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biseccion.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(633, 466)
        Dialog.setStyleSheet("background-color: #e1e1e1;")
        Dialog.setModal(True)
        self.btnCalcular = QtWidgets.QPushButton(Dialog)
        self.btnCalcular.setGeometry(QtCore.QRect(510, 360, 111, 91))
        self.btnCalcular.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: #fff;\n"
"font-size: 14px;")
        self.btnCalcular.setObjectName("btnCalcular")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 360, 251, 91))
        self.groupBox.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.groupBox.setObjectName("groupBox")
        self.txtInferior = QtWidgets.QLineEdit(self.groupBox)
        self.txtInferior.setGeometry(QtCore.QRect(10, 50, 113, 29))
        self.txtInferior.setStyleSheet("background-color: #fff;\n"
"color: #000;")
        self.txtInferior.setObjectName("txtInferior")
        self.txtSuperior = QtWidgets.QLineEdit(self.groupBox)
        self.txtSuperior.setGeometry(QtCore.QRect(130, 50, 113, 29))
        self.txtSuperior.setStyleSheet("background-color: #fff;\n"
"color: #000;")
        self.txtSuperior.setObjectName("txtSuperior")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 55, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(130, 30, 55, 17))
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 611, 331))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background-color: rgb(157, 157, 157)")
        self.groupBox_2.setObjectName("groupBox_2")
        self.txtEcuacion = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtEcuacion.setGeometry(QtCore.QRect(10, 50, 341, 131))
        self.txtEcuacion.setStyleSheet("background-color: #fff;\n"
"color: #000;\n"
"font-size: 14px;")
        self.txtEcuacion.setObjectName("txtEcuacion")
        self.btnCerrar = QtWidgets.QPushButton(self.groupBox_2)
        self.btnCerrar.setGeometry(QtCore.QRect(554, 10, 51, 29))
        self.btnCerrar.setStyleSheet("color: white;\n"
"background-color:rgb(255, 0, 0);")
        self.btnCerrar.setObjectName("btnCerrar")
        self.btnGraficar = QtWidgets.QPushButton(self.groupBox_2)
        self.btnGraficar.setGeometry(QtCore.QRect(10, 190, 341, 29))
        self.btnGraficar.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: #fff;\n"
"font-size: 14px;")
        self.btnGraficar.setObjectName("btnGraficar")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 50, 245, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnExponente = QtWidgets.QPushButton(self.layoutWidget)
        self.btnExponente.setObjectName("btnExponente")
        self.gridLayout.addWidget(self.btnExponente, 0, 0, 1, 1)
        self.btnRaiz = QtWidgets.QPushButton(self.layoutWidget)
        self.btnRaiz.setObjectName("btnRaiz")
        self.gridLayout.addWidget(self.btnRaiz, 0, 1, 1, 1)
        self.btnParentesis = QtWidgets.QPushButton(self.layoutWidget)
        self.btnParentesis.setObjectName("btnParentesis")
        self.gridLayout.addWidget(self.btnParentesis, 0, 2, 1, 1)
        self.btnPor = QtWidgets.QPushButton(self.layoutWidget)
        self.btnPor.setObjectName("btnPor")
        self.gridLayout.addWidget(self.btnPor, 2, 0, 1, 1)
        self.btnCos = QtWidgets.QPushButton(self.layoutWidget)
        self.btnCos.setObjectName("btnCos")
        self.gridLayout.addWidget(self.btnCos, 1, 0, 1, 1)
        self.btnSen = QtWidgets.QPushButton(self.layoutWidget)
        self.btnSen.setObjectName("btnSen")
        self.gridLayout.addWidget(self.btnSen, 1, 1, 1, 1)
        self.btnTan = QtWidgets.QPushButton(self.layoutWidget)
        self.btnTan.setObjectName("btnTan")
        self.gridLayout.addWidget(self.btnTan, 1, 2, 1, 1)
        self.btnEntre = QtWidgets.QPushButton(self.layoutWidget)
        self.btnEntre.setObjectName("btnEntre")
        self.gridLayout.addWidget(self.btnEntre, 2, 1, 1, 1)
        self.btnMas = QtWidgets.QPushButton(self.layoutWidget)
        self.btnMas.setObjectName("btnMas")
        self.gridLayout.addWidget(self.btnMas, 2, 2, 1, 1)
        self.btnMenos = QtWidgets.QPushButton(self.layoutWidget)
        self.btnMenos.setObjectName("btnMenos")
        self.gridLayout.addWidget(self.btnMenos, 3, 0, 1, 1)
        self.btnX = QtWidgets.QPushButton(self.layoutWidget)
        self.btnX.setObjectName("btnX")
        self.gridLayout.addWidget(self.btnX, 3, 2, 1, 1)
        self.btnPi = QtWidgets.QPushButton(self.layoutWidget)
        self.btnPi.setObjectName("btnPi")
        self.gridLayout.addWidget(self.btnPi, 3, 1, 1, 1)
        self.btnEF = QtWidgets.QPushButton(self.layoutWidget)
        self.btnEF.setObjectName("btnEF")
        self.gridLayout.addWidget(self.btnEF, 4, 0, 1, 1)
        self.btnLog = QtWidgets.QPushButton(self.layoutWidget)
        self.btnLog.setObjectName("btnLog")
        self.gridLayout.addWidget(self.btnLog, 4, 2, 1, 1)
        self.btnLn = QtWidgets.QPushButton(self.layoutWidget)
        self.btnLn.setObjectName("btnLn")
        self.gridLayout.addWidget(self.btnLn, 4, 1, 1, 1)
        self.txtEcuacionR = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtEcuacionR.setGeometry(QtCore.QRect(0, 230, 601, 91))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.txtEcuacionR.setFont(font)
        self.txtEcuacionR.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txtEcuacionR.setStyleSheet("\n"
"background-color: #fff;\n"
"color: #000;\n"
"font-size: 14px;\n"
"text-align: relative;\n"
"margin-left: 10px;")
        self.txtEcuacionR.setFrameShadow(QtWidgets.QFrame.Raised)
        self.txtEcuacionR.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtEcuacionR.setReadOnly(True)
        self.txtEcuacionR.setObjectName("txtEcuacionR")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 360, 120, 91))
        self.groupBox_3.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.txtTolerancia = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtTolerancia.setGeometry(QtCore.QRect(10, 50, 101, 31))
        self.txtTolerancia.setStyleSheet("background-color: #fff;\n"
"color: #000;")
        self.txtTolerancia.setText("")
        self.txtTolerancia.setObjectName("txtTolerancia")
        self.btnLimpiar = QtWidgets.QPushButton(Dialog)
        self.btnLimpiar.setGeometry(QtCore.QRect(400, 360, 101, 91))
        self.btnLimpiar.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: #fff;\n"
"font-size: 14px")
        self.btnLimpiar.setObjectName("btnLimpiar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txtEcuacion, self.btnGraficar)
        Dialog.setTabOrder(self.btnGraficar, self.txtInferior)
        Dialog.setTabOrder(self.txtInferior, self.txtSuperior)
        Dialog.setTabOrder(self.txtSuperior, self.txtTolerancia)
        Dialog.setTabOrder(self.txtTolerancia, self.btnCalcular)
        Dialog.setTabOrder(self.btnCalcular, self.btnLimpiar)
        Dialog.setTabOrder(self.btnLimpiar, self.btnCerrar)
        Dialog.setTabOrder(self.btnCerrar, self.btnExponente)
        Dialog.setTabOrder(self.btnExponente, self.btnRaiz)
        Dialog.setTabOrder(self.btnRaiz, self.btnParentesis)
        Dialog.setTabOrder(self.btnParentesis, self.btnPor)
        Dialog.setTabOrder(self.btnPor, self.btnCos)
        Dialog.setTabOrder(self.btnCos, self.btnSen)
        Dialog.setTabOrder(self.btnSen, self.btnTan)
        Dialog.setTabOrder(self.btnTan, self.btnEntre)
        Dialog.setTabOrder(self.btnEntre, self.btnMas)
        Dialog.setTabOrder(self.btnMas, self.btnMenos)
        Dialog.setTabOrder(self.btnMenos, self.btnX)
        Dialog.setTabOrder(self.btnX, self.btnPi)
        Dialog.setTabOrder(self.btnPi, self.btnEF)
        Dialog.setTabOrder(self.btnEF, self.txtEcuacionR)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Método de Bisección"))
        self.btnCalcular.setText(_translate("Dialog", "Calcular Raíz"))
        self.groupBox.setTitle(_translate("Dialog", "Intervalos"))
        self.label.setText(_translate("Dialog", "Inferior"))
        self.label_2.setText(_translate("Dialog", "Superior"))
        self.groupBox_2.setTitle(_translate("Dialog", "Ecuación"))
        self.btnCerrar.setText(_translate("Dialog", "Cerrar"))
        self.btnGraficar.setText(_translate("Dialog", "Graficar Función"))
        self.btnExponente.setText(_translate("Dialog", "x^2"))
        self.btnRaiz.setText(_translate("Dialog", "sqrt( x )"))
        self.btnParentesis.setText(_translate("Dialog", "( )"))
        self.btnPor.setText(_translate("Dialog", "*"))
        self.btnCos.setText(_translate("Dialog", "cos( x )"))
        self.btnSen.setText(_translate("Dialog", "sin( x )"))
        self.btnTan.setText(_translate("Dialog", "tan( x )"))
        self.btnEntre.setText(_translate("Dialog", "/"))
        self.btnMas.setText(_translate("Dialog", "+"))
        self.btnMenos.setText(_translate("Dialog", "-"))
        self.btnX.setText(_translate("Dialog", "X"))
        self.btnPi.setText(_translate("Dialog", "π"))
        self.btnEF.setText(_translate("Dialog", "e^x"))
        self.btnLog.setText(_translate("Dialog", "log( x )"))
        self.btnLn.setText(_translate("Dialog", "ln( x )"))
        self.groupBox_3.setTitle(_translate("Dialog", "Tolerancia"))
        self.btnLimpiar.setText(_translate("Dialog", "Limpiar"))

